optim_args:
  learning_rate: 0.0003
  weight_decay: 0.0001
  momentum: 0.9
  batch_size: 512
  use_sgd: false
data_args:
  k: 3
  seq_length: 256
  fixed_special_toks: true
  special_toks_offset: 0
  no_repeat: false
  bos_num: 1
  delimiter_p: 0.0
  delim_num: 1
  mix_p: null
model_args:
  vocab_size: 67
  n_layers: 3
  dim: 256
  n_heads: 1
  max_length: 256
  pre_norm: true
  no_attn_norm: []
  no_ffn_norm: []
  no_ffn: []
  no_attn: []
  no_norm: false
  linear_ffn: []
  no_first_layer_ffn: false
  freeze_embeddings: false
  freeze_output: false
  tie_output: false
  freeze_wv: false
  freeze_wo: false
  no_wo: false
  no_wv: false
  sin_cos: false
wandb_args:
  project: birth_dynamics
  entity: tianyu_guo
  name: dormant_copy_long_train
max_iters: 100000
eval_delta: 5
log_norms: false
log_probes: true
num_data_workers: 24
save_dir: /data/tianyu/birth/gens/pre-iclr/dynamics/dormant_copy_long_train/model_L3_H1_bos1_delim0
fine_grid_log: 100000
root_dir: ''
task_name: dormant_copy
seperate_loss: true
seed: 42
