optim_args:
  learning_rate: 0.0003
  weight_decay: 0.0001
  momentum: 0.9
  batch_size: 512
  use_sgd: false
data_args:
  k: 5
  seq_length: 256
  show_latents: false
  fixed_special_toks: true
  special_toks_offset: 0
  output_counter: true
  no_repeat: false
  bos_num: 1
  delimiter_p: 0.02
model_args:
  vocab_size: 67
  n_layers: 3
  dim: 256
  n_heads: 4
  max_length: 256
  pre_norm: true
  no_ffn: false
  no_norm: false
  linear_ffn: false
  no_first_layer_ffn: false
  freeze_embeddings: false
  freeze_output: false
  tie_output: false
  freeze_wv: false
  freeze_wo: false
  no_wo: false
  no_wv: false
  sin_cos: false
  bos_num: 1
max_iters: 5000
eval_delta: 5
log_norms: false
log_probes: true
num_data_workers: 60
save_dir: /data/tianyu_guo/birth/gens/delim/model_L3_H4_lr3-4_bos1_delim002
root_dir: ''
