optim_args:
  learning_rate: 0.0003
  weight_decay: 0.0001
  momentum: 0.9
  batch_size: 512
  use_sgd: false
data_args:
  k: 3
  seq_length: 256
  fixed_special_toks: true
  special_toks_offset: 0
  no_repeat: false
  bos_num: 1
  delimiter_p: 0.0
  delim_num: 1
  mix_p: 0.5
model_args:
  vocab_size: 67
  n_layers: 1
  dim: 256
  n_heads: 1
  max_length: 256
  pre_norm: true
  no_ffn: false
  no_norm: false
  linear_ffn: false
  no_first_layer_ffn: false
  freeze_embeddings: false
  freeze_output: false
  tie_output: false
  freeze_wv: false
  freeze_wo: false
  no_wo: false
  no_wv: false
  sin_cos: false
  bos_num: 1
wandb_args:
  project: birth
  entity: tianyu_guo
  name: dormant_copy_interpolate
max_iters: 10000
eval_delta: 5
log_norms: false
log_probes: true
num_data_workers: 60
save_dir: /data/tianyu/birth/gens/final/dormant_copy_interpolate_seed28/model_L1_H1_bos1_delim0_mix_p0500
fine_grid_log: 0
root_dir: ''
task_name: dormant_copy_interpolate
seperate_loss: true
seed: 53
